User:
  name: Aquiles

DAQ:
  name: AnalogDaq # Choose DummyDaq or AnalogDaq
  port: /dev/ttyACM1 # (OR COM3, etc)
  resistance: 220ohm

Scan:
  start: 0mV
  stop: 3.3V
  step: 400mV
  channel_out: 0
  channel_in: 0
  delay: 50ms

Save:
  folder: /home/aquiles/Data
  filename: IV_data
